[mysql]
status = true
name = "books_shop"
host = "mysql-db"
post = "3306"
password = "MyS3cr3t"

[redis]
address = "redis:6379"
password = ""
db = 0
key = "top_books"
channel_book = "book"
channel_category = "category"

[mongodb]
status = false
url = "mongo:27017"
username = "root"
password = "root"
auth_source = "admin"
database = "BookShop"
connection_book = "book"
connection_category ="category"
connection_group_book ="groupbook"

[postgres]
status = false
host ="postgres"
name = "postgres"
post = "5432"
user = "postgres"
password = "root"

[http_pubsub]
status = "false"
