[mysql]
status = true
name = "books_shop"
host = "127.0.0.1"
post = "30306"
password = "My:S3cr3t/"

[redis]
address = "localhost:6379"
password = ""
db = 0
key = "top_books"
channel_book = "book"
channel_category = "category"

[mongodb]
status = false
url = "localhost:27017"
username = "root"
password = "root"
auth_source = "admin"
database = "BookShop"
connection_book = "book"
connection_category ="category"
connection_group_book ="groupbook"

[postgres]
status = false
host ="127.0.0.1"
name = "postgres"
post = "5432"
user = "postgres"
password = "root"

[http_pubsub]
status = "true"
